<?php

namespace App\Enums;

enum AuthErrorCode: string
{
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case WRONG_PASSWORD = 'WRONG_PASSWORD';
    case EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    case PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case MISSING_CONTACT_INFO = 'MISSING_CONTACT_INFO';
    case SERVER_ERROR = 'SERVER_ERROR';
    case UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS';
} 